<?
/*$APPLICATION->AddHeadScript(SITE_TEMPLATE_PATH."/site_files/plugins/fancybox2/lib/jquery.mousewheel-3.0.6.pack.js");
$APPLICATION->AddHeadScript(SITE_TEMPLATE_PATH."/site_files/plugins/fancybox2/source/jquery.fancybox.js?v=2.1.5");
$APPLICATION->AddHeadScript(SITE_TEMPLATE_PATH."/site_files/plugins/fancybox2/source/helpers/jquery.fancybox-buttons.js?v=1.0.5");
$APPLICATION->AddHeadScript(SITE_TEMPLATE_PATH."/site_files/plugins/fancybox2/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7");
$APPLICATION->AddHeadScript(SITE_TEMPLATE_PATH."/site_files/plugins/fancybox2/source/helpers/jquery.fancybox-media.js?v=1.0.6");
$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH."/site_files/plugins/fancybox2/source/jquery.fancybox.css?v=2.1.5");
$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH."/site_files/plugins/fancybox2/source/helpers/jquery.fancybox-buttons.css?v=1.0.5");
$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH."/site_files/plugins/fancybox2/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7");*/
?>